server:
  port: ${SERVER_PORT}
  #address: ${SERVER_ADDRESS}
  servlet:
    context-path: /prefactura
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    pre-factura:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_HOST}/${DB_SCHEMA}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hibernate-hbm2ddl-auto: update
      show-sql: true
    soa-alt:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_ALT}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
    soa-vir:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@${DB_HOST_SOA_VIR}:${DB_PORT_SOA}:${DB_SCHEMA_SOA}
      username: ${USERNAME_SOA}
      password: ${PASSWORD_SOA}
      hibernate-hbm2ddl-auto: none
